trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      # ref: refs/tags/v0.1.0-alpha.2
      ref: refs/heads/master # TODO you may want to change it to refs/tags/TAG_NAME.
      endpoint: PipelinesTemplates # TODO YOU NEED TO CHANGE THIS!

stages: 
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/scenarios/check.yml@rust_pipelines
    parameters: # You can make conditions here.
      cargo-check: true
      cargo-check-nigtly: true # this can fail and stage check still succeed
      cargo-clippy: true
      rustfmt: true

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  - template: ci/scenarios/test.yml@rust_pipelines
    parameters:
      min_rust_supported: 1.31
