parameters:
  noDefaultFeatures: '--no-default-features'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - script: cargo check ${{ parameters.noDefaultFeatures }} --features ${{ feature }}
    displayName: Check features = ${{ feature }}

  - ${{ if parameters.benches }}:
    - script: cargo check --benches --all
      displayName: Check benchmarks
