jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  container: ${{ parameters.container }}
  steps:
  - script: cargo check --all 
    displayName: Check source

  - script: cargo check --tests --all 
    displayName: Check tests
